name:  onepiece
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_speed_dial: ^7.0.0 
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  flutter_animate: ^4.4.0
  shared_preferences: ^2.2.2 #dependencia para que se guarden las cosas cerrando la app
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.17.5
  intl: ^0.18.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  


flutter:
  uses-material-design: true

  assets:
    - assets/
