// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN0ZBYXjSSyhirt1HtwbQOGd-zYnk9hok',
    appId: '1:691789547121:web:72dc88a0ab347c0fb1fdd0',
    messagingSenderId: '691789547121',
    projectId: 'onepiecewiki-d5189',
    authDomain: 'onepiecewiki-d5189.firebaseapp.com',
    storageBucket: 'onepiecewiki-d5189.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15RT7EXb2X5MBN9OmVK4K7uUyz39eScs',
    appId: '1:691789547121:android:b1ad4ee65a47171cb1fdd0',
    messagingSenderId: '691789547121',
    projectId: 'onepiecewiki-d5189',
    storageBucket: 'onepiecewiki-d5189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjYnkWIqo2sHyNrmWPdA29PG1Jx6xWX4E',
    appId: '1:691789547121:ios:eb3dc8fd050b7e67b1fdd0',
    messagingSenderId: '691789547121',
    projectId: 'onepiecewiki-d5189',
    storageBucket: 'onepiecewiki-d5189.firebasestorage.app',
    iosBundleId: 'com.example.onepiece',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjYnkWIqo2sHyNrmWPdA29PG1Jx6xWX4E',
    appId: '1:691789547121:ios:eb3dc8fd050b7e67b1fdd0',
    messagingSenderId: '691789547121',
    projectId: 'onepiecewiki-d5189',
    storageBucket: 'onepiecewiki-d5189.firebasestorage.app',
    iosBundleId: 'com.example.onepiece',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN0ZBYXjSSyhirt1HtwbQOGd-zYnk9hok',
    appId: '1:691789547121:web:424c746ab4a9a5b6b1fdd0',
    messagingSenderId: '691789547121',
    projectId: 'onepiecewiki-d5189',
    authDomain: 'onepiecewiki-d5189.firebaseapp.com',
    storageBucket: 'onepiecewiki-d5189.firebasestorage.app',
  );
}
